### ISSUE TITLE
Failing to update entry with new fiels

### ISSUE THREAD

**Issue by iroth** [contentful/contentful-management.py#10]
Scenario: I have an entry with fields A,B. Added a new field C to content model.
All my entries have field C empty.
Now trying to update an entry with field C fails with: exception No field with id "null" found

seems the problem is in: update->create_attributes->to_json->fields_with_locale->_real_field_id_for
returning None for that new field

**Comment by dlitvakb** [comment]
Hey @iroth,

I'll try to reproduce and let you know how it goes.

Cheers

**Comment by iroth** [comment]
thanks @dlitvakb - any update?

**Comment by dlitvakb** [comment]
Hey @iroth,

I was traveling and couldn't finish investigating, will try again today.

Cheers

**Comment by dlitvakb** [comment]
Hey @iroth,

Are you trying to update an already fetched entry after updating the CT?

**Comment by dlitvakb** [comment]
I think I found the issue,

When a field was not present on the `raw` entry, and you tried to serialize it with a new field that was not originally present, it would fail to get the proper field ID.

What I'm going to have to do, is that, if the ID is not found on the `raw` entry, it will try to fetch it from the Content Type and re-add it to the `raw` so that all fields are up-to-date.

Cheers

**Comment by dlitvakb** [comment]
PR #15 has been submitted and should fix this issue.

Once that is merged a new release will be done.

Cheers

**Comment by iroth** [comment]
thanks @dlitvakb - will test once a release is available

**Comment by iroth** [comment]
any ETA for release? thanks!

**Comment by dlitvakb** [comment]
This has just been released as version 1.3.1
