### ISSUE TITLE
entry.is_published() throws an exception

### ISSUE THREAD

**Issue by iroth** [contentful/contentful-management.py#11]
this line of code in resource.py throws an exception:
        return bool(self.sys.get('published_at', False))
'bool' object is not callable

**Comment by iroth** [comment]
published_at = entry.sys.get('published_at', False)
if published_at:
   # do what ever - ex. entry.unpublish()

**Comment by dlitvakb** [comment]
Hey @iroth,

Looks like a bug, let me check onto it and I'll get back to you ASAP.

Cheers

**Comment by dlitvakb** [comment]
Hey @iroth,

I've looked into it, it's not a bug.

`is_published` is a property. Therefore not called with parenthesis, which is why it's returning an error when you're trying to call a `bool` object. https://github.com/contentful/contentful-management.py/blob/master/contentful_management/resource.py#L326RL330

Cheers

**Comment by iroth** [comment]
thanks @dlitvakb - my bad, working now!
