### ISSUE TITLE
update only some fields in entry

### ISSUE THREAD

**Issue by iroth** [contentful/contentful-management.py#23]
Trying to update only few fields (and actually just one locale version of them, but this might not be related). Other fields becomes empty (using the latest 1.4.0 version).
I am calling these:
        content_entries = content_type.entries().all({'fields.our_code': our_code})
        if len(content_entries) > 0:
            entry = content_entries[0]
            existingValue = entry.fieldA
            entry.update(
                attributes={
                    'fields': {'fieldA':{'en-US': existingValue, 'he-IL': translatedValue}
                }
            )
this works and I see the new translated value, but fieldB becomes empty

**Comment by dlitvakb** [comment]
Hey @iroth,

Using `entry.update(attributes)` will replace the content of the entry with the content of the attributes sent.

The easiest way update content, is to do it using the setters for each property and then calling `entry.save()`. For example:

```python
entry.fieldA = "some value"
entry.fieldB = "something else"
entry.save()
```

By doing this, you avoid having to explicitly mention all of the fields on the `update` call as it is handled internally, keeping all the values in the fields.

Hope this helps,

Cheers

**Comment by iroth** [comment]
Hi @dlitvakb - thanks for the quick response, but how do I update just the 'he-IL' locale entry?
Is there a setter per locale?

**Comment by iroth** [comment]
OK, figured it out:
entry.default_locale = 'he-IL'
entry.fieldA = localizedValue
entry.save()

**Comment by dlitvakb** [comment]
Hey @iroth,

Yes either that or `entry.locale = 'he-IL'`. Both will properly work.

Cheers

**Comment by iroth** [comment]
I beleive this gave me an error of missing attribute. In addition, two more issues I faced:
1. If the field did not have an English (default locale) entry, I could not add a Hebrew one without first creating an empty English one
2. There are still issues with camelCase vs. snake_case name of fields. In Contentful I had all my field ids as camelCase, and adding that missing value for English mentioned above did not work both if I tried camelCase or snake_case in setAttr. The setAttr call was fine, but the API returned "No such field" error. I had to change the field ID in Contentful to be snake_case (which most likely will break other clients in JavaScript).

**Comment by dlitvakb** [comment]
Hey @iroth,

Regarding the non-english locale, that's because you're not instantiating the client with `default_locale='he-IL'`, it doesn't require you to have english, it's only that  it's the default value, so unless you specify it otherwise, it will try to default to english.

Regarding your second point, the `snake_case` is only internal to the library, but when sent back to the API it uses the API-set IDs (whatever they are, even custom set ones), and not the `snake_cased` versions. Therefore, could you please show me what's the code you're using to bypass this?

Cheers

**Comment by iroth** [comment]
hey @dlitvakb - thanks for the prompt response. Will try using the client with the default locale as you propose. Will try to recreate the snake_case issue for you

**Comment by erikgreif-acc** [comment]
I am trying to do something like this, but I am dealing with entries fetched using `contentType.entries().all(query={...})` where I am using the `select` query to retrieve only certain fields. This is necessary because of the volume of entries being retrieved, and the size of each entry.

The problem I encounter, is when I want to flip a boolean and then use `save()` as mentioned earlier, the fields I did not select in my initial query are pushed as if they have no value assigned to them. It seems there is a PUT operation involved, but I would expect it to be a PATCH operation since the `save()` function shouldn't save fields I haven't changed. 

Is there any interest in enabling a PATCH capability, or are there any ways for me to do it today without fetching the entry in its entirety just to flip a boolean?

**Comment by dlitvakb** [comment]
Hey @erikgreif-acc,

Sadly, there's no PATCH endpoint available, therefore you either have to do `entry.reload()`, then update the value then `entry.save()`, or avoid using the `select` operator when doing batch updates.

I'll forward the request for a PATCH endpoint so that partial updates are possible in the future.

Cheers

**Comment by erikgreif-acc** [comment]
@dlitvakb Thank you. Using `entry.reload()` is a good option for me.
